version: "3.7"
services:
  oneul:
    build: .
    ports:
      - 5555:5555
    depends_on:
      - mysql
      - redis
      - mongodb
      - kafka
      
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: oneul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
       - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "post:1:1"