spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        ddl-auto: update
        hbm2ddl:
          auto: update
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: "sa"
  redis:
    host: 127.0.0.1
    port: 6379

server:
  servlet:
    session:
      timeout: 60

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG

log-in-page: www.naver.com